### ISSUE TITLE
Error when using HEBO sampler

### ISSUE THREAD

**Issue by db0** [optuna/optunahub-registry#184]
### Expected behavior

I used HEBO on my script which worked fine using the autosampler: https://github.com/Haidra-Org/hordelib/blob/training/train.py 

It worked for 5 trials, and then gave an exception as I describe below.

I run this on two processes.

### Environment

- The package of OptunaHub which you are using:
- Optuna version: 4.10
- OptunaHub version: 0.10
- Python version: 3.10.12
- OS: Ubuntu 22.04
- (Optional) Other libraries and their versions:
* torch: 2.5.1+cu124

### Error messages, stack traces, or logs

```shell
I am getting this error when running using the HEBO sampler, but not immediately. It succeeded a few studies, but eventually got this exception


[W 2024-11-19 20:56:09,587] Trial 6 failed with parameters: {} because of the following error: AssertionError().
Traceback (most recent call last):
  File "/home/db0/.local/lib/python3.10/site-packages/hebo/optimizers/hebo.py", line 143, in suggest
    model.fit(X, Xe, y)
  File "/home/db0/.local/lib/python3.10/site-packages/hebo/models/gp/gp.py", line 74, in fit
    Xc, Xe, y = filter_nan(Xc, Xe, y, 'all')
  File "/home/db0/.local/lib/python3.10/site-packages/hebo/models/util.py", line 19, in filter_nan
    assert x  is None or torch.isfinite(x).all()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/db0/.local/lib/python3.10/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/home/db0/projects/hordelib/train.py", line 539, in objective
    # Network topology
  File "/home/db0/.local/lib/python3.10/site-packages/optuna/_convert_positional_args.py", line 83, in converter_wrapper
    return func(**kwargs)  # type: ignore[call-arg]
  File "/home/db0/.local/lib/python3.10/site-packages/optuna/trial/_trial.py", line 324, in suggest_int
    suggested_value = int(self._suggest(name, distribution))
  File "/home/db0/.local/lib/python3.10/site-packages/optuna/trial/_trial.py", line 627, in _suggest
    elif self._is_relative_param(name, distribution):
  File "/home/db0/.local/lib/python3.10/site-packages/optuna/trial/_trial.py", line 659, in _is_relative_param
    if name not in self.relative_params:
  File "/home/db0/.local/lib/python3.10/site-packages/optuna/trial/_trial.py", line 71, in relative_params
    self._relative_params = self.study.sampler.sample_relative(
  File "/home/db0/.cache/optunahub/api.github.com/optuna/optunahub-registry/main/package/samplers/hebo/sampler.py", line 28, in sample_relative
    params_pd = self._hebo.suggest()
  File "/home/db0/.local/lib/python3.10/site-packages/hebo/optimizers/hebo.py", line 147, in suggest
    model.fit(X, Xe, y)
  File "/home/db0/.local/lib/python3.10/site-packages/hebo/models/gp/gp.py", line 74, in fit
    Xc, Xe, y = filter_nan(Xc, Xe, y, 'all')
  File "/home/db0/.local/lib/python3.10/site-packages/hebo/models/util.py", line 19, in filter_nan
    assert x  is None or torch.isfinite(x).all()
AssertionError
[W 2024-11-19 20:56:09,587] Trial 6 failed with value None.
Traceback (most recent call last):
  File "/home/db0/projects/hordelib/train.py", line 721, in <module>
    # Create SQLite connection string
  File "/home/db0/projects/hordelib/train.py", line 677, in main
    )
  File "/home/db0/.local/lib/python3.10/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/db0/.local/lib/python3.10/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/db0/.local/lib/python3.10/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/db0/.local/lib/python3.10/site-packages/optuna/study/_optimize.py", line 209, in _run_trial
    frozen_trial = _tell_with_warning(
  File "/home/db0/.local/lib/python3.10/site-packages/optuna/study/_tell.py", line 181, in _tell_with_warning
    study.sampler.after_trial(study, frozen_trial, state, values)
  File "/home/db0/.cache/optunahub/api.github.com/optuna/optunahub-registry/main/package/samplers/hebo/sampler.py", line 42, in after_trial
    self._hebo.observe(pd.DataFrame([trial.params]), np.asarray([values]))
  File "/home/db0/.local/lib/python3.10/site-packages/hebo/optimizers/abstract_optimizer.py", line 65, in observe
    self.observe_new_data(x, y)
  File "/home/db0/.local/lib/python3.10/site-packages/hebo/optimizers/hebo.py", line 211, in observe_new_data
    valid_id = np.where(np.isfinite(y.reshape(-1)))[0].tolist()
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
```


### Steps to reproduce

1. clone this branch https://github.com/Haidra-Org/hordelib/blob/training/train.py 
2. Run train.py


### Additional context (optional)

Apologies if this is the wrong place to post this issue but I can't find any other location.

**Comment by nabenabe0928** [comment]
The search space feeded to HEBO must be adapted to your usecase.

https://github.com/Haidra-Org/hordelib/blob/training/train.py#L79-L82

Like this:

```python
from optuna.distributions import CategoricalDistribution
from optuna.distributions import FloatDistribution
from optuna.distributions import IntDistribution

search_space = {
    "learning_rate": FloatDistribution(MIN_LEARNING_RATE, MAX_LEARNING_RATE, log=True),
    "weight_decay": FloatDistribution(MIN_WEIGHT_DECAY, MAX_WEIGHT_DECAY, log=True),
    "batch_size": CategoricalDistribution(batch_sizes),
    "optimizer": CategoricalDistribution(["Adam", "RMSprop", "SGD"]),
    "hidden_layers": IntDistribution(MIN_HIDDEN_LAYERS, MAX_HIDDEN_LAYERS, log=True)
    ...
}
```

But it seems that your search_space includes conditional parameters, which are `f"dropout_l{i}"` and `f"hidden_layer_{i}_size"`.
Since HEBO does not support dynamic search space (i.e. a search space with conditional parameters), we cannot actually use HEBO for your search space.

**Comment by db0** [comment]
Thank you so much for the reply. So if I drop conditional parameters I should be able to use HEBO the way you pointed?

**Comment by nabenabe0928** [comment]
> So if I drop conditional parameters I should be able to use HEBO the way you pointed?

Yes, you can.

> how do I use it then?

You do not use the `search_space` variable, but `HEBOSampler` internally uses this variable to instantiate `HEBO` because `HEBO` is an external library and it requires a pre-defined search space.

In your case, the provided pre-defined search space only has `x` and `y`, while the objective function says we have many other parameters.
As HEBO was only told that we search for `x` and `y` in the beginning, but your objective function tells HEBO needs to search for much more parameters after the initialization, HEBO was simply confused.

To avoid this problem, `search_space` given to `HEBOSampler` must be consistent with the search space that can be inferred from the objective function.

**Comment by db0** [comment]
OK, so I'm able to do like this as well?

```
HEBOSampler = optunahub.load_module("samplers/hebo").HEBOSampler
OPTUNA_SAMPLER = HEBOSampler(
{
    "learning_rate": FloatDistribution(MIN_LEARNING_RATE, MAX_LEARNING_RATE, log=True),
    "weight_decay": FloatDistribution(MIN_WEIGHT_DECAY, MAX_WEIGHT_DECAY, log=True),
    "batch_size": CategoricalDistribution(batch_sizes),
    "optimizer": CategoricalDistribution(["Adam", "RMSprop", "SGD"]),
    "hidden_layers": IntDistribution(MIN_HIDDEN_LAYERS, MAX_HIDDEN_LAYERS, log=True)
}
)
```

**Comment by nabenabe0928** [comment]
@db0 

> OK, so I'm able to do like this as well?

Yeap, you can do like this.

But please note that the keys provided in `search_space` and the parameter names suggested in the objective function must be identical.
 
## Good Example

```python
def objective(trial: optuna.Trial) -> float:
    x = trial.suggest_float("x", -1, 1)
    y = trial.suggest_float("y", -1, 1)
    return x**2 + y**2


search_space = {
    "x": optuna.distributions.FloatDistribution(-1, 1),
    "y": optuna.distributions.FloatDistribution(-1, 1),
}
```

## Bad Examples

```python
def objective(trial: optuna.Trial) -> float:
    x = trial.suggest_float("x", -1, 1)
    # y is lacking.
    return x**2

def objective(trial: optuna.Trial) -> float:
    # x is lacking.
    y = trial.suggest_float("y", -1, 1)
    return y**2

search_space = {
    "x": optuna.distributions.FloatDistribution(-1, 1),
    "y": optuna.distributions.FloatDistribution(-1, 1),
}
```

```python
def objective(trial: optuna.Trial) -> float:
    x = trial.suggest_float("x", -1, 1)
    y = trial.suggest_float("y", -1, 1)
    return x**2 + y**2

search_space = {
    # x is lacking.
    "y": optuna.distributions.FloatDistribution(-1, 1),
}
search_space = {
    "x": optuna.distributions.FloatDistribution(-1, 1),
    # y is lacking.
}
```

**Comment by db0** [comment]
Thanks! I implemented all your suggestions and [this is the code I'm running it with now](https://github.com/Haidra-Org/hordelib/blob/training/train.py) in case anyone is interested.
