### ISSUE TITLE
[samplers/hebo] `HEBOSampler` currently requires python version `<=3.11`.

### ISSUE THREAD

**Issue by eukaryo** [optuna/optunahub-registry#226]
### Expected behavior

`$pip install hebo` works.

### Environment

- The package of OptunaHub which you are using: N/A
- Optuna version: N/A
- OptunaHub version: N/A
- Python version: 3.12
- OS: Windows 11 Pro with WSL2
- (Optional) Other libraries and their versions: N/A

### Error messages, stack traces, or logs

```shell
Collecting hebo
  Downloading HEBO-0.3.6-py3-none-any.whl.metadata (4.6 kB)
Collecting numpy<1.25,>=1.16 (from hebo)
  Downloading numpy-1.24.4.tar.gz (10.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 40.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/mnt/c/2024-11-05/v312env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/mnt/c/2024-11-05/v312env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/c/2024-11-05/v312env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/mnt/c/2024-11-05/v312env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 999, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-rb_jglj_/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-rb_jglj_/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-rb_jglj_/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
```

### Steps to reproduce

$ python3.12 -m venv v312env
$ . v312env/bin/activate
$ pip install hebo

### Additional context (optional)

There is an issue (https://github.com/huawei-noah/HEBO/issues/76) in the HEBO repository. After this issue is solved, we will be able to use HEBOSampler in Python3.12.

**Comment by y0z** [comment]
FYI: A workaround is available.
https://github.com/huawei-noah/HEBO/issues/112#issuecomment-3415791411

**Comment by y0z** [comment]
I'll close this issue, as HEBO isn't actively maintained to fix it, and we've added the workaround description.
<img width="672" height="116" alt="Image" src="https://github.com/user-attachments/assets/878ad57d-4529-4f5e-ae05-bdcbc9c54521" />
